name: github pages

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.5.2
          with:
            cache: npm
        - run: npm install
        - run: npm build
        - run: npm start
